name: pull

inputs:
  gh_user: 
    required: true
  gh_token:
    required: true
  gh_org:
    required: true
  gh_repo:
    required: true

runs:
  using: "composite"
  steps:
  - name: git pull
    shell: bash
    run: |
      cd /mnt/efs/${{ inputs.gh_repo }}
      echo "HR ${{ github.sha }}"
      if [[ ! -f "pull.${{ github.sha }}" ]]; then
        touch "pull.${{ github.sha }}"
        git config --global --add safe.directory /mnt/efs/${{ inputs.gh_repo }}
        git remote set-url origin https://${{ inputs.gh_user }}:${{ inputs.gh_token }}@github.com/${{ inputs.gh_org }}/${{ inputs.gh_repo }}.git
        git status --porcelain 1>&2
        if [ $(git status --porcelain |  grep -v '??'  | wc -l) -eq 0 ]; then
          echo "PULL"
          git pull
        fi
        if [ $(git status --porcelain | grep 'D' | wc -l) -gt 0 ]; then
          echo "RESET PULL"
          git reset --hard origin/master
          git pull
        fi
        echo "END PULL"
      else
        echo "NO PULL" 1>&2
      fi

