name: pull

inputs:
  gh_user: 
    required: true
  gh_token:
    required: true
  gh_org:
    required: true
  gh_repo:
    required: true

runs:
  using: "composite"
  steps:
  - name: git pull
    shell: bash
    run: |
      cd /mnt/efs/${{ inputs.gh_repo }}
      # echo "HR ${{ github.sha }}"
      # if [[ ! -f "/mnt/efs/pull.${{ github.sha }}" ]]; then
        # ls -la /mnt/efs 1>&2
        # ls -la /mnt/efs/${{ inputs.gh_repo }} 1>&2
        # whoami 1>&2
        # touch "/mnt/efs/pull.${{ github.sha }}"
        #chmod 777 "/mnt/efs/pull.${{ github.sha }}"
        git config --global --add safe.directory /mnt/efs/${{ inputs.gh_repo }}
        git remote set-url origin https://${{ inputs.gh_user }}:${{ inputs.gh_token }}@github.com/${{ inputs.gh_org }}/${{ inputs.gh_repo }}.git
        git status --porcelain 1>&2
        if [ $(git status --porcelain |  grep -v '??'  | wc -l) -eq 0 ]; then
          echo "PULL" 1>&2
          git pull origin/master
        fi
        if [ $(git status --porcelain | grep 'D' | wc -l) -gt 0 ]; then
          echo "RESET PULL" 1>&2
          git reset --hard origin/master
          git pull
        fi
        echo "END PULL" 1>&2
      # else
        # echo "NO PULL" 1>&2
      # fi

