name: pull

inputs:
  gh_user: 
    required: true
  gh_token:
    required: true
  gh_org:
    required: true
  gh_repo:
    required: true

runs:
  using: "composite"
  steps:
  - name: git pull
    shell: bash
    run: |
      cd /mnt/efs/${{ inputs.gh_repo }}
      git config --global --add safe.directory /mnt/efs/${{ inputs.gh_repo }}
      git remote set-url origin https://${{ inputs.gh_user }}:${{ inputs.gh_token }}@github.com/${{ inputs.gh_org }}/${{ inputs.gh_repo }}.git
      if [ $(git status --porcelain |  grep -v '??' | wc -l) -eq "0" ]; then
        echo "PULL" 1>&2
        git pull
      fi
      echo "END PULL" 1>&2

