name: clone

inputs:
  gh_user: 
    required: true
  gh_token:
    required: true
  gh_org:
    required: true
  gh_repo:
    required: true

runs:
  using: "composite"
  steps:
  - name: git clone
    shell: bash
    run: |
      cd /mnt/efs 
      # git config --global --add safe.directory /mnt/efs/.cargo/registry/index/github.com-1ecc6299db9ec823/.git
      git clone https://${{ inputs.gh_user }}:${{ inputs.gh_token }}@github.com/${{ inputs.gh_org }}/${{ inputs.gh_repo }}
