name: s3store

inputs:
  source: 
    required: true
  destination:
    required: true
  gh_repo:
    required: true
  run_nr:
    required: false
  root_dir:
    default: /mnt/efs

runs:
  using: "composite"
  steps:
  - name: s3 retrieve
    shell: bash
    run: |
      cd ${{ inputs.root_dir }}/${{ inputs.gh_repo }}
      if [[ -z ${{ inputs.run_nr }} ]]; then
        aws s3 cp ${{ inputs.source }}.${{ github.run_number }} ${{ inputs.destination }} 
      else
        aws s3 cp ${{ inputs.source }}.${{ inputs.run_nr }} ${{ inputs.destination }} 
      fi
