name: cleanup_runner

runs:
  using: "composite"
  steps:
  - name: kill runner
    shell: bash
    run: |
        echo "******** Exiting ********"
        PID=`ps -ef | grep run.sh | grep -v grep | sed 's/  */:/g' | cut -d: -f 2` 
        kill $PID
