name: s3store

inputs:
  source: 
    required: true
  destination:
    required: true
  gh_repo:
    required: true
  root_dir:
    default: /mnt/efs

runs:
  using: "composite"
  steps:
  - name: s3 store
    shell: bash
    run: |
      cd ${{ inputs.root_dir }}/${{ inputs.gh_repo }}
      aws s3 cp ${{ inputs.source }} ${{ inputs.destination }}.${{ github.run_number }}
      rm -f ${{ inputs.source }}
